version: '2.1'

services:
  node:
    image: next-typescript-workspace
    build:
      context: .
      dockerfile: ./.docker/node.dev.dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000