version: '2.1'

services:
  node:
    image: next-typescript-workspace
    build:
      context: .
      dockerfile: ./.docker/node.dev.dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src/pages:/usr/src/app/src/pages
      - ./src/server:/usr/src/app/src/server
      - ./src/shared:/usr/src/app/src/shared
      - ./src/static:/usr/src/app/src/static
      - ./src/types:/usr/src/app/src/types
    ports:
      - 3000:3000
